apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivapp2-deployment
  namespace: trivapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivapp2
  template:
    metadata:
      labels:
        app: trivapp2
    spec:
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - image: asia-south1-docker.pkg.dev/triv-case/triv-repo/trivapp2:latest
        name: app2
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
