apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivapp1-deployment
  namespace: trivapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivapp1
  template:
    metadata:
      labels:
        app: trivapp1
    spec:
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - image: asia-south1-docker.pkg.dev/triv-case/triv-repo/trivapp1:latest
        name: app1
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          appArmorProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - NET_RAW
            - SYS_ADMIN
            - SYS_MODULE
            - SYS_TIME
            - SYS_BOOT
            - SYS_RESOURCE
            - SYS_PTRACE
            - CHOWN
            - FSETID
            - KILL
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
