apiVersion: v1
kind: Service
metadata:
  name: trivapp2-service
  namespace: trivapp-namespace
spec:
  type: ClusterIP
  selector:
    app: trivapp2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080