name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK (gcloud)
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.GKE_ARTIFACT_REGISTRY }}/trivapp2:latest .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push ${{ secrets.GKE_ARTIFACT_REGISTRY }}/trivapp2:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK (gcloud)
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      - name: Install gke-gcloud-auth-plugin for use with kubectl
        run: |
            gcloud components install gke-gcloud-auth-plugin
            gcloud container clusters get-credentials triv-cluster --region=asia-south1 

      - name: Set up GKE credentials
        run: |
          gcloud container clusters get-credentials triv-cluster --region asia-south1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/
